version: '3.8'
services:
  influxdb:
    image: "arm32v7/influxdb:latest"
### WARNUNG: keine sichere Installation von Influxdb, ports nicht freigeben oder für Sicherheit sorgen ###
#    ports:
#      - "8086:8086"
    restart: always

  grafana:
    image: "grafana/grafana-oss:latest"
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    restart: always

  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"
    volumes:
      - "nodered:/data"
    restart: always

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always

#### zigbee usb stick wird benötigt. die addresse suchen und hier anpassen. ####
#  zigbee2mqtt:
#    container_name: zigbee2mqtt
#    image: koenkk/zigbee2mqtt
#    restart: unless-stopped
#    volumes:
#      - ./zigbee/data:/app/data
#      - /run/udev:/run/udev:ro
#    ports:
#      - 8080:8080
#    environment:
#      - TZ=Europe/Berlin
#    devices:
#      - /dev/ttyUSB0:/dev/ttyACM0

volumes:
  grafana:
  victron:
  nodered:
