version: '3.4'
services:
  victron:
    image: "victronenergy/venus-docker-server:2.4.0"
# Ports können nach dem Einrichten gesperrt werden
    ports:
      - "8088:8088"
    volumes:
      - "victron:/config"
    restart: always

  influxdb:
    image: "arm32v7/influxdb:latest"
# WARNUNG: keine sichere Installation von Influxdb, ports nicht freigeben oder für Sicherheit sorgen
#    ports:
#      - "8086:8086"
    restart: always

  grafana:
    image: "grafana/grafana-oss:latest"
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    restart: always

  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"
    volumes:
      - "nodered:/data"
    restart: always

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always

#### zigbee usb stick wird benötigt. mit lsusb die addresse suchen und hier anpassen. ####

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0


#### Weitere Dienste zum Testen ####

#  homeassistant:
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    ports:
#      - "8123:8123"
#    volumes:
#      - ./homeassistant:/config
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    privileged: true



#  openhab:
#    image: "openhab/openhab:3.2.0"
#    ports:
#      - "8080:8080"
#      - "8443:8443"
#    restart: always
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#      - "./openhab_addons:/openhab/addons"
#      - "./openhab_conf:/openhab/conf"
#      - "./openhab_userdata:/openhab/userdata"
#    environment:
#      OPENHAB_HTTP_PORT: "8080"
#      OPENHAB_HTTPS_PORT: "8443"
#      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"

#  iobroker:
#    image: buanet/iobroker
#    restart: always
#    ports:
#      - "8081:8081"
#    volumes:
#      - "./iobrokerdata:/opt/iobroker"




volumes:
  grafana:
  victron:
  nodered:
